# Copyright 2025 Open Source Robotics Foundation, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

load("@crate_opaque_types//:defs.bzl", all_crate_deps_opaque_types = "all_crate_deps")
load("@crate_zenoh//:defs.bzl", all_crate_deps_crate_zenoh = "all_crate_deps")
load("@rules_rust//cargo:defs.bzl", "cargo_bootstrap_repository", "cargo_build_script")
load("@rules_rust//rust:defs.bzl", "rust_binary", "rust_library")
load("@rules_cc//cc:defs.bzl", "cc_test")
load("@rules_foreign_cc//foreign_cc:defs.bzl", "cmake")
load("//:rules.bzl", "cargo_build_stdout_capture")

package(default_visibility = ["//visibility:public"])

rust_library(
    name = "opaque_types",
    srcs = ["build-resources/opaque-types/src/lib.rs"],
    crate_features = [
        "auth_pubkey",
        "auth_usrpwd",
        "panic",
        "shared-memory",
        "transport_multilink",
        "transport_compression",
        "transport_quic",
        "transport_serial",
        "transport_tcp",
        "transport_tls",
        "transport_udp",
        "transport_unixsock-stream",
        "transport_ws",
        "unstable"
    ],
    deps = all_crate_deps_opaque_types(build = True, normal = True),
)

cargo_build_script(
    name = "build_script",
    srcs = glob([
        "build.rs",
        "buildrs/**",
    ]),
    data = glob([
        "build-resources/opaque-types/**",
        "cbindgen.toml",
        "Cargo.toml",
        "include/**",
        "splitguide.yaml",
        "version.txt",
        "src/**",
    ]),
    crate_root = "build.rs",
    deps = all_crate_deps_crate_zenoh(build = True, normal = True) + [
        "@rules_rust//rust/runfiles",
    ],
    rundir = "."
)

# rust_binary_without_process_wrapper(
#     name = "process_wrapper",
#     srcs = glob(["*.rs"]),
#     allocator_libraries = select({
#         "@rules_rust//rust/settings:experimental_use_allocator_libraries_with_mangled_symbols_on":
#             "@rules_rust//ffi/rs:allocator_libraries_with_mangling_support_without_process_wrapper",
#         "//conditions:default":
#             "@rules_rust//ffi/rs:empty_allocator_libraries",
#     }),
#     edition = "2018",
#     # To ensure the process wrapper is produced deterministically
#     # debug info, which is known to sometimes have host specific
#     # paths embedded in this section, is stripped out.
#     rustc_flags = select({
#         ":opt_linux": ["-Cstrip=debuginfo"],
#         ":opt_macos": ["-Cstrip=debuginfo"],
#         "//conditions:default": [],
#     }),
#     visibility = ["//visibility:public"],
#     deps = [
#         "@rules_rust_tinyjson//:tinyjson",
#     ],
# )

# # We compile the crate but through a process wrapper that ignores failures
# # and pipes stderr to a file that we can then use subsequently.
# rust_library(
#     name = "opaque_types",
#     srcs = ["build-resources/opaque-types/src/lib.rs"],
#     crate_features = [
#         "panic",
#         "shared-memory",
#         "zenoh/transport_serial",
#     ],
#     deps = all_crate_deps(
#         normal = True,
#     ),
#     "_process_wrapper" = ":process_wrapper",
# )


# filegroup(
#     name = "srcs",
#     srcs = glob(["**"], exclude=[
#         # Platform dependent generated files
#         "include/zenoh_configure.h",
#         "include/zenoh_opaque.h",
#         # Build resources
#         ".build_resources/**",
#         "src/opaque_types/mod.rs",
#         # Bazel files
#         "BUILD.bazel",
#         "MODULE.bazel",
#         "MODULE.bazel.lock"]
#     ),
# )

# cmake(
#     name = "zenoh-c",
#     cache_entries = {
#         "ZENOHC_CARGO_FLAGS" : "--features=shared-memory zenoh/transport_serial",
#         "ZENOHC_BUILD_WITH_UNSTABLE_API" : "TRUE",
#     },
#     lib_source = ":srcs",
#     out_static_libs = ["libzenohc.a"],
#     out_include_dir = "include",
# )

# [
#     cc_test(
#         name = 'test_' + name.removesuffix('_test'),
#         srcs = [       
#             "tests/z_int_helpers.h",
#             "tests/" + name + ".c"
#         ],
#         copts = [
#             "-Wno-unused-variable",
#             "-Wno-missing-braces"
#         ],
#         deps = [":zenoh-c"],
#         timeout = "short"
#     )
#     for name in [
#         "z_api_config_test",
#         "z_api_constants",
#         "z_api_double_drop_test",
#         "z_api_drop_options",
#         "z_api_encoding_test",
#         "z_api_keyexpr_drop_test",
#         "z_api_keyexpr_test",
#         "z_api_liveliness",
#         "z_api_null_drop_test",
#         "z_api_payload_test",
#         "z_api_session_test",
#         "z_api_shm_test",
#         "z_api_unitinialized_check",
#     ]
# ]